name: Go CD Pipeline

on:
  workflow_run:
    workflows: ["Go CI Pipeline"]
    types:
      - completed

jobs:
  deploy-server:
    runs-on: self-hosted
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'v') 
    # ^ this checks if the head_branch of a git push starts with v or no (if its a version release the head breach would have a v0.0.1 declaration )
    # if the head_branch isnt starting with a v infront of it, that will mean the head_branch is surely named main ( if it wasnt the ci wont even run )
    # and the cd gets cancled, becuase the push request is a commit, not a version release
    # git push origin main (the main here is the head_branch)

    steps:

      - name: Checkout the exact tagged commit
        uses: actions/checkout@v7
        with:
          clean: true
          ref: ${{ github.event.workflow_run.head_sha }} #is to prevent branch commit code merging with version release,
          # by only grabbing the sha that causes the cd workflow to trigger, by default acions/checkout@v7 always grabs the latest
          #commit, that being a commit to the main branch not a version release will also be caught and added into the released codebase.
          #this here prevents this by only grabbing the sha that caused the cd to trriger and commit the changes and codebase of the version release,
          
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: matthew552/sclera #pulls my docker image
          flavor: |
           latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.workflow_run.head_branch }} 
            # sets the tag as the tag provided in head_branch

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: . #uses the exisitng Dockerfile into the codebase to build the new versions image and uploads it to docker hub
          push: true
          tags: ${{ steps.meta.outputs.tags }} #makes use of the provided tag from head_branch 
          annotations: ${{ steps.meta.outputs.annotations }}

      
        # composes and hosts the server to the local computer
      - name: Hosting the server
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose up -d
