name: Go CD Pipeline

on:
  workflow_run:
    workflows: ["Go CI Pipeline"]
    types:
      - completed

jobs:
  deploy-server:
    runs-on: self-hosted
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'v')

    steps:

      - name: Checkout the exact tagged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: matthew552/sclera
          flavor: |
           latest=false
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.workflow_run.head_branch }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.workflow_run.head_branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}


        #todo
        
        #fix github pushing err that assigns of same annotain ( v0.0.0 ) without pushing the imagae first

        #understand if a 0.0 ver is acc needed or not by reading claudes explanation, and take action accordingly
        
        #then faafsafsaafasfasfass

        #release v0.1

        #after the image getting pushed to hub, make a docker network, run a container, run a postgreSQL container (if no exists in network)
        #make them talk to eachother and deploy to localhost (my local cloud)